// Centralized role ids mirrored from contracts/libs/Roles.sol. Keep in sync with onchain constants.
export const Roles = {
  COHORT_REVENUE_ROUTER_ROLE: 1n,
  COHORT_INVESTMENT_RECORDER_ROLE: 2n,
  VALUABLE_ACTION_REGISTRY_ISSUER_ROLE: 3n,
  VALUABLE_ACTION_SBT_MANAGER_ROLE: 4n,
  VALUABLE_ACTION_SBT_GOVERNANCE_ROLE: 5n,
  REVENUE_ROUTER_DISTRIBUTOR_ROLE: 6n,
  REVENUE_ROUTER_POSITION_MANAGER_ROLE: 7n,
  COMMUNITY_TOKEN_MINTER_ROLE: 8n,
  COMMUNITY_TOKEN_TREASURY_ROLE: 9n,
  COMMUNITY_TOKEN_EMERGENCY_ROLE: 10n,
  MEMBERSHIP_TOKEN_MINTER_ROLE: 11n,
  MEMBERSHIP_TOKEN_GOVERNANCE_ROLE: 12n,
  COMMERCE_DISPUTES_CALLER_ROLE: 13n,
  HOUSING_MARKETPLACE_CALLER_ROLE: 14n,
  VERIFIER_MANAGER_CALLER_ROLE: 15n,
};
